version: '3.8'

services:
  # Scheduled data ingestion service (runs every 6 hours)
  spotify-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spotify-scheduler
    command: python3 scheduler.py
    restart: unless-stopped
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - REDIRECT_URI=${REDIRECT_URI:-http://127.0.0.1:8888/callback}
      - BRONZE_PATH=/app/data/bronze
      - KAGGLE_CSV=/app/data/kaggle/dataset.csv
      - TOKEN_PATH=/app/data/.spotify_tokens.json
      - SPARK_MASTER=local[*]
      - SPARK_DRIVER_MEMORY=4g
      - SPARK_EXECUTOR_MEMORY=4g
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=python3
      - ALLOW_SYNTHETIC=${ALLOW_SYNTHETIC:-true}
    volumes:
      - ./data:/app/data
      - ./clients:/app/clients
      - ./config:/app/config
      - ./loaders:/app/loaders
      - ./mappers:/app/mappers
      - ./schemas:/app/schemas
      - ./scripts:/app/scripts
      - ./utils:/app/utils
      - ./writers:/app/writers
      - ./run_ingestion.py:/app/run_ingestion.py
      - ./scheduler.py:/app/scheduler.py
    ports:
      - "8888:8888"
    networks:
      - spotify-network
    mem_limit: 6g
    memswap_limit: 6g

  # One-time manual ingestion service
  spotify-pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spotify-analytics
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - REDIRECT_URI=${REDIRECT_URI:-http://127.0.0.1:8888/callback}
      - BRONZE_PATH=/app/data/bronze
      - KAGGLE_CSV=/app/data/kaggle/dataset.csv
      - TOKEN_PATH=/app/data/.spotify_tokens.json
      - SPARK_MASTER=local[*]
      - SPARK_DRIVER_MEMORY=4g
      - SPARK_EXECUTOR_MEMORY=4g
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=python3
      - ALLOW_SYNTHETIC=${ALLOW_SYNTHETIC:-true}
    volumes:
      - ./data:/app/data
      - ./clients:/app/clients
      - ./config:/app/config
      - ./loaders:/app/loaders
      - ./mappers:/app/mappers
      - ./schemas:/app/schemas
      - ./scripts:/app/scripts
      - ./utils:/app/utils
      - ./writers:/app/writers
      - ./run_ingestion.py:/app/run_ingestion.py
    ports:
      - "8888:8888"
    networks:
      - spotify-network
    mem_limit: 6g
    memswap_limit: 6g
    profiles:
      - manual  # Only runs when explicitly called

networks:
  spotify-network:
    driver: bridge
